openapi: 3.0.0
info:
  title: E-Commerce Auth API
  version: 1.0.0
  description: Auth endpoints for signup and login

paths:
  /api/auth/signup:
    post:
      tags:
        - Auth
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [name, email, password]
              properties:
                name:
                  type: string
                  example: John Doe
                email:
                  type: string
                  example: john@example.com
                password:
                  type: string
                  example: strongpassword
      responses:
        "201":
          description: User registered successfully
        "400":
          description: Bad request

  /api/auth/login:
    post:
      tags:
        - Auth
      summary: Login user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, password]
              properties:
                email:
                  type: string
                  example: john@example.com
                password:
                  type: string
                  example: strongpassword
      responses:
        "200":
          description: Login successful
        "400":
          description: Invalid credentials
  /api/auth/logout:
    post:
      tags:
        - Auth
      summary: Logout a user
      description: Blacklists JWT token via Redis for 24 hours
      responses:
        "200":
          description: Logout successful
        "400":
          description: Missing token
        "500":
          description: Server error
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []
